# -*- coding: utf-8 -*-
"""YoloV5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZRK3R8RNNnYoHEsCpog7cKui137wNyy
"""

!nvidia-smi

"""### DOWN YOLOV5 LIBRARY FROM GITHUB


"""

!git clone https://github.com/ultralytics/yolov5

"""### INSTALL LIBRARY YOLO-V5 AND SUPPORTED OTHER"""

!pip install -r /content/drive/MyDrive/YoloV5/yolov5-master/requirements.txt

"""### UNRAR IMAGES AND LABELS FILE TO TRAIN """

!unrar x /content/drive/MyDrive/Data_set_finger/Data.rar

"""### TRAINING MODEL YOLOV5"""

!python /content/drive/MyDrive/YoloV5/yolov5-master/train.py --img 460 --batch 16 --epochs 50 --data /content/drive/MyDrive/YoloV5/yolov5-master/data/coco128.yaml --weights /content/drive/MyDrive/YoloV5/yolov5-master/runs/train/exp2/weights/last.pt

!python /content/drive/MyDrive/YoloV5/yolov5-master/train.py --img 640 --batch 16 --epochs 10 --data /content/drive/MyDrive/YoloV5/yolov5-master/data/coco128.yaml --weights /content/drive/MyDrive/YoloV5/yolov5-master/runs/train/exp3/weights/last.pt

"""### DETECT VIDEO BY WEIGHTS FILE"""

!python /content/drive/MyDrive/YoloV5/yolov5-master/detect.py --source /content/drive/MyDrive/VideoDetect/ML2.mp4 --weights /content/drive/MyDrive/YoloV5/yolov5-master/runs/train/exp2/weights/best.pt